load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "gtest",
  urls = ["https://github.com/google/googletest/archive/9bb354fa8325fa31faa1e12627b25ab445e6eed3.zip"],
  strip_prefix = "googletest-9bb354fa8325fa31faa1e12627b25ab445e6eed3",
)

